/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface QuotationDetails {
    terms: string;
    description: string;
    approvalTimestamp?: bigint;
    approved: boolean;
    replyFile?: ExternalBlob;
    price: bigint;
}
export interface OfficeLocation {
    lat: number;
    lon: number;
    address: string;
}
export interface AdminUser {
    principal?: Principal;
    active: boolean;
    registrationTimestamp: bigint;
    registrationMethod: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface VideoClip {
    id: string;
    serviceType: string;
    thumbnailUrl: string;
    description: string;
    videoUrl: string;
}
export interface AdminInvitationEntry {
    invitedBy?: Principal;
    email: string;
    invitationTimestamp: bigint;
    hashedPassword: string;
    registrationMethod: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface NegotiationMessage {
    sender: string;
    message: string;
    timestamp: bigint;
}
export interface QuotationRequest {
    id: string;
    status: QuotationStatus;
    serviceType: ServiceType;
    customer: Principal;
    mobileNumber: string;
    deadline: bigint;
    email: string;
    designStatus: DesignStatus;
    negotiationHistory: Array<NegotiationMessage>;
    timestamp: bigint;
    projectDetails: string;
}
export interface AdminContent {
    aboutPageContent: string;
    contactInfo: ContactInfo;
    businessHours: Array<string>;
    homepageContent: string;
    services: Array<string>;
    gallery: Array<string>;
}
export interface ChatMessage {
    id: string;
    senderIsOwner: boolean;
    messageText: string;
    isReply: boolean;
    originalMessageId?: string;
    replyToMessageId?: string;
    timestamp: bigint;
    senderName: string;
    senderEmail: string;
}
export interface DeliveryConfig {
    minimumFee: bigint;
    perKmRate: bigint;
}
export interface ServiceImage {
    id: string;
    serviceType: string;
    description: string;
    imageUrl: string;
}
export interface Project {
    id: string;
    title: string;
    dateCompleted: bigint;
    description: string;
    imageUrl: string;
    category: ServiceType;
}
export interface ContactInfo {
    mapsLink: string;
    email: string;
    physicalAddress: string;
    phone: string;
}
export interface Review {
    id: string;
    customerName: string;
    projectType: ServiceType;
    reviewText: string;
    imageUrl?: string;
    submissionDate: bigint;
    rating: bigint;
}
export interface UserProfile {
    name: string;
    mobileNumber: string;
    email: string;
}
export enum DesignStatus {
    needed = "needed",
    ready = "ready"
}
export enum QuotationStatus {
    customerPending = "customerPending",
    completed = "completed",
    rejected = "rejected",
    workInProgress = "workInProgress",
    accepted = "accepted",
    draft = "draft",
    negotiating = "negotiating",
    paymentPending = "paymentPending"
}
export enum ServiceType {
    banner = "banner",
    offset = "offset",
    design = "design",
    digital = "digital"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addInternetIdentityAdmin(principal: Principal): Promise<void>;
    addProject(imageUrl: string, title: string, description: string, category: ServiceType): Promise<string>;
    addQuotationDetails(quotationId: string, price: bigint, description: string, terms: string): Promise<void>;
    addReplyFile(quotationId: string, file: ExternalBlob): Promise<void>;
    addReview(customerName: string, reviewText: string, rating: bigint, imageUrl: string | null, projectType: ServiceType): Promise<string>;
    addServiceImage(serviceType: string, imageUrl: string, description: string): Promise<string>;
    addVideoClip(serviceType: string, videoUrl: string, thumbnailUrl: string, description: string): Promise<string>;
    adminAcceptPayment(quotationId: string): Promise<void>;
    approveQuotation(quotationId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateCustomer(identifier: string, passwordHash: string): Promise<string>;
    calculateDeliveryFee(distance: bigint): Promise<bigint>;
    createQuotationRequest(serviceType: ServiceType, deadline: bigint, projectDetails: string, mobileNumber: string, email: string, designStatus: DesignStatus): Promise<string>;
    customerApproveQuotation(quotationId: string): Promise<void>;
    deleteProject(projectId: string): Promise<void>;
    deleteServiceImage(imageId: string): Promise<void>;
    deleteVideoClip(clipId: string): Promise<void>;
    editProject(projectId: string, imageUrl: string, title: string, description: string, category: ServiceType): Promise<void>;
    getAdminContent(): Promise<AdminContent | null>;
    getAdminInvitations(): Promise<Array<AdminInvitationEntry>>;
    getAdminPrincipals(): Promise<Array<AdminUser>>;
    getAdminUserCount(): Promise<bigint>;
    getAllChatMessages(): Promise<Array<ChatMessage>>;
    getAllProjects(): Promise<Array<Project>>;
    getAllQuotations(): Promise<Array<QuotationRequest>>;
    getAllReviews(): Promise<Array<Review>>;
    /**
     * / Query the current app name (publicly available).
     */
    getAppName(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatsForCustomer(senderEmail: string): Promise<Array<ChatMessage>>;
    getContactInfo(): Promise<ContactInfo>;
    getCustomerChatHistory(senderEmail: string): Promise<{
        messages: Array<ChatMessage>;
        replies: Array<ChatMessage>;
    }>;
    getCustomerQuotations(customerId: string): Promise<Array<QuotationRequest>>;
    getDeliveryConfig(): Promise<DeliveryConfig>;
    getLogo(): Promise<ExternalBlob | null>;
    getMyQuotations(): Promise<Array<QuotationRequest>>;
    getOfficeLocation(): Promise<OfficeLocation | null>;
    getPendingQuotationsOlderThan1Hour(): Promise<Array<string>>;
    getProjectsByCategory(category: ServiceType): Promise<Array<Project>>;
    getQuotationDetails(quotationId: string): Promise<QuotationDetails | null>;
    getQuotationStatistics(): Promise<{
        customerPending: bigint;
        completed: bigint;
        rejected: bigint;
        workInProgress: bigint;
        accepted: bigint;
        draft: bigint;
        negotiating: bigint;
        paymentPending: bigint;
    }>;
    getReplyFile(quotationId: string): Promise<ExternalBlob | null>;
    getReviewsByRating(rating: bigint): Promise<Array<Review>>;
    getServiceImages(): Promise<Array<ServiceImage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVideoClips(): Promise<Array<VideoClip>>;
    handleQuotationResponse(quotationId: string, status: QuotationStatus, message: string | null): Promise<void>;
    inviteAdminUser(email: string, hashedPassword: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markQuotationCustomerPending(quotationId: string): Promise<void>;
    ownerReply(replyToMessageId: string, replyText: string): Promise<string>;
    registerBiometric(email: string): Promise<void>;
    registerCustomer(email: string, mobileNumber: string, passwordHash: string): Promise<string>;
    respondToNegotiation(quotationId: string, message: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(senderName: string, senderEmail: string, messageText: string): Promise<string>;
    /**
     * / Set the app name (admin only).
     */
    setAppName(name: string): Promise<void>;
    setDeliveryConfig(perKmRate: bigint, minimumFee: bigint): Promise<void>;
    setLogo(_logo: ExternalBlob): Promise<void>;
    setOfficeLocation(_location: OfficeLocation): Promise<void>;
    updateAdminContent(newContactInfo: ContactInfo, services: Array<string>, businessHours: Array<string>, gallery: Array<string>, homepageContent: string, aboutPageContent: string): Promise<void>;
    updateContactInfo(email: string, phone: string, physicalAddress: string, mapsLink: string): Promise<void>;
    verifyAuthentication(email: string, hashedPassword: string): Promise<boolean>;
}
import type { AdminContent as _AdminContent, AdminInvitationEntry as _AdminInvitationEntry, AdminUser as _AdminUser, ChatMessage as _ChatMessage, DesignStatus as _DesignStatus, ExternalBlob as _ExternalBlob, NegotiationMessage as _NegotiationMessage, OfficeLocation as _OfficeLocation, Project as _Project, QuotationDetails as _QuotationDetails, QuotationRequest as _QuotationRequest, QuotationStatus as _QuotationStatus, Review as _Review, ServiceType as _ServiceType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addInternetIdentityAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInternetIdentityAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInternetIdentityAdmin(arg0);
            return result;
        }
    }
    async addProject(arg0: string, arg1: string, arg2: string, arg3: ServiceType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addQuotationDetails(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuotationDetails(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuotationDetails(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addReplyFile(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReplyFile(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReplyFile(arg0, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addReview(arg0: string, arg1: string, arg2: bigint, arg3: string | null, arg4: ServiceType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addServiceImage(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceImage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceImage(arg0, arg1, arg2);
            return result;
        }
    }
    async addVideoClip(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoClip(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoClip(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAcceptPayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAcceptPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAcceptPayment(arg0);
            return result;
        }
    }
    async approveQuotation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveQuotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveQuotation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateCustomer(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateCustomer(arg0, arg1);
            return result;
        }
    }
    async calculateDeliveryFee(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateDeliveryFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateDeliveryFee(arg0);
            return result;
        }
    }
    async createQuotationRequest(arg0: ServiceType, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: DesignStatus): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotationRequest(to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_DesignStatus_n14(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotationRequest(to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_DesignStatus_n14(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async customerApproveQuotation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.customerApproveQuotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.customerApproveQuotation(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteServiceImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceImage(arg0);
            return result;
        }
    }
    async deleteVideoClip(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoClip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoClip(arg0);
            return result;
        }
    }
    async editProject(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ServiceType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editProject(arg0, arg1, arg2, arg3, to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProject(arg0, arg1, arg2, arg3, to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async getAdminContent(): Promise<AdminContent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminContent();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminContent();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminInvitations(): Promise<Array<AdminInvitationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminInvitations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminInvitations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminPrincipals(): Promise<Array<AdminUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipals();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipals();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserCount();
            return result;
        }
    }
    async getAllChatMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChatMessages();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChatMessages();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuotations(): Promise<Array<QuotationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotations();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotations();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppName(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppName();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppName();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatsForCustomer(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatsForCustomer(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatsForCustomer(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInfo(): Promise<ContactInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return result;
        }
    }
    async getCustomerChatHistory(arg0: string): Promise<{
        messages: Array<ChatMessage>;
        replies: Array<ChatMessage>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerChatHistory(arg0);
                return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerChatHistory(arg0);
            return from_candid_record_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerQuotations(arg0: string): Promise<Array<QuotationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerQuotations(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerQuotations(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryConfig(): Promise<DeliveryConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryConfig();
            return result;
        }
    }
    async getLogo(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogo();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogo();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuotations(): Promise<Array<QuotationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuotations();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuotations();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficeLocation(): Promise<OfficeLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficeLocation();
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficeLocation();
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingQuotationsOlderThan1Hour(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingQuotationsOlderThan1Hour();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingQuotationsOlderThan1Hour();
            return result;
        }
    }
    async getProjectsByCategory(arg0: ServiceType): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectsByCategory(to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectsByCategory(to_candid_ServiceType_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationDetails(arg0: string): Promise<QuotationDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationDetails(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationDetails(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotationStatistics(): Promise<{
        customerPending: bigint;
        completed: bigint;
        rejected: bigint;
        workInProgress: bigint;
        accepted: bigint;
        draft: bigint;
        negotiating: bigint;
        paymentPending: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotationStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotationStatistics();
            return result;
        }
    }
    async getReplyFile(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplyFile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplyFile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByRating(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByRating(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByRating(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceImages(): Promise<Array<ServiceImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceImages();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVideoClips(): Promise<Array<VideoClip>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoClips();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoClips();
            return result;
        }
    }
    async handleQuotationResponse(arg0: string, arg1: QuotationStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.handleQuotationResponse(arg0, to_candid_QuotationStatus_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.handleQuotationResponse(arg0, to_candid_QuotationStatus_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async inviteAdminUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteAdminUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteAdminUser(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markQuotationCustomerPending(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markQuotationCustomerPending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markQuotationCustomerPending(arg0);
            return result;
        }
    }
    async ownerReply(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.ownerReply(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ownerReply(arg0, arg1);
            return result;
        }
    }
    async registerBiometric(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBiometric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBiometric(arg0);
            return result;
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async respondToNegotiation(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToNegotiation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToNegotiation(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async setAppName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppName(arg0);
            return result;
        }
    }
    async setDeliveryConfig(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeliveryConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeliveryConfig(arg0, arg1);
            return result;
        }
    }
    async setLogo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLogo(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLogo(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setOfficeLocation(arg0: OfficeLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOfficeLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOfficeLocation(arg0);
            return result;
        }
    }
    async updateAdminContent(arg0: ContactInfo, arg1: Array<string>, arg2: Array<string>, arg3: Array<string>, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminContent(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminContent(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateContactInfo(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactInfo(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyAuthentication(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAuthentication(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAuthentication(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AdminInvitationEntry_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminInvitationEntry): AdminInvitationEntry {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_AdminUser_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUser): AdminUser {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_DesignStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignStatus): DesignStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Project_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_QuotationDetails_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationDetails): Promise<QuotationDetails> {
    return await from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationRequest): QuotationRequest {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_QuotationStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuotationStatus): QuotationStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminContent]): AdminContent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OfficeLocation]): OfficeLocation | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuotationDetails]): Promise<QuotationDetails | null> {
    return value.length === 0 ? null : await from_candid_QuotationDetails_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invitedBy: [] | [Principal];
    email: string;
    invitationTimestamp: bigint;
    hashedPassword: string;
    registrationMethod: string;
}): {
    invitedBy?: Principal;
    email: string;
    invitationTimestamp: bigint;
    hashedPassword: string;
    registrationMethod: string;
} {
    return {
        invitedBy: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.invitedBy)),
        email: value.email,
        invitationTimestamp: value.invitationTimestamp,
        hashedPassword: value.hashedPassword,
        registrationMethod: value.registrationMethod
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: [] | [Principal];
    active: boolean;
    registrationTimestamp: bigint;
    registrationMethod: string;
}): {
    principal?: Principal;
    active: boolean;
    registrationTimestamp: bigint;
    registrationMethod: string;
} {
    return {
        principal: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.principal)),
        active: value.active,
        registrationTimestamp: value.registrationTimestamp,
        registrationMethod: value.registrationMethod
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    senderIsOwner: boolean;
    messageText: string;
    isReply: boolean;
    originalMessageId: [] | [string];
    replyToMessageId: [] | [string];
    timestamp: bigint;
    senderName: string;
    senderEmail: string;
}): {
    id: string;
    senderIsOwner: boolean;
    messageText: string;
    isReply: boolean;
    originalMessageId?: string;
    replyToMessageId?: string;
    timestamp: bigint;
    senderName: string;
    senderEmail: string;
} {
    return {
        id: value.id,
        senderIsOwner: value.senderIsOwner,
        messageText: value.messageText,
        isReply: value.isReply,
        originalMessageId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.originalMessageId)),
        replyToMessageId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.replyToMessageId)),
        timestamp: value.timestamp,
        senderName: value.senderName,
        senderEmail: value.senderEmail
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    dateCompleted: bigint;
    description: string;
    imageUrl: string;
    category: _ServiceType;
}): {
    id: string;
    title: string;
    dateCompleted: bigint;
    description: string;
    imageUrl: string;
    category: ServiceType;
} {
    return {
        id: value.id,
        title: value.title,
        dateCompleted: value.dateCompleted,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_ServiceType_n31(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _QuotationStatus;
    serviceType: _ServiceType;
    customer: Principal;
    mobileNumber: string;
    deadline: bigint;
    email: string;
    designStatus: _DesignStatus;
    negotiationHistory: Array<_NegotiationMessage>;
    timestamp: bigint;
    projectDetails: string;
}): {
    id: string;
    status: QuotationStatus;
    serviceType: ServiceType;
    customer: Principal;
    mobileNumber: string;
    deadline: bigint;
    email: string;
    designStatus: DesignStatus;
    negotiationHistory: Array<NegotiationMessage>;
    timestamp: bigint;
    projectDetails: string;
} {
    return {
        id: value.id,
        status: from_candid_QuotationStatus_n36(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n31(_uploadFile, _downloadFile, value.serviceType),
        customer: value.customer,
        mobileNumber: value.mobileNumber,
        deadline: value.deadline,
        email: value.email,
        designStatus: from_candid_DesignStatus_n38(_uploadFile, _downloadFile, value.designStatus),
        negotiationHistory: value.negotiationHistory,
        timestamp: value.timestamp,
        projectDetails: value.projectDetails
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    projectType: _ServiceType;
    reviewText: string;
    imageUrl: [] | [string];
    submissionDate: bigint;
    rating: bigint;
}): {
    id: string;
    customerName: string;
    projectType: ServiceType;
    reviewText: string;
    imageUrl?: string;
    submissionDate: bigint;
    rating: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        projectType: from_candid_ServiceType_n31(_uploadFile, _downloadFile, value.projectType),
        reviewText: value.reviewText,
        imageUrl: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.imageUrl)),
        submissionDate: value.submissionDate,
        rating: value.rating
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<_ChatMessage>;
    replies: Array<_ChatMessage>;
}): {
    messages: Array<ChatMessage>;
    replies: Array<ChatMessage>;
} {
    return {
        messages: from_candid_vec_n24(_uploadFile, _downloadFile, value.messages),
        replies: from_candid_vec_n24(_uploadFile, _downloadFile, value.replies)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    terms: string;
    description: string;
    approvalTimestamp: [] | [bigint];
    approved: boolean;
    replyFile: [] | [_ExternalBlob];
    price: bigint;
}): Promise<{
    terms: string;
    description: string;
    approvalTimestamp?: bigint;
    approved: boolean;
    replyFile?: ExternalBlob;
    price: bigint;
}> {
    return {
        terms: value.terms,
        description: value.description,
        approvalTimestamp: record_opt_to_undefined(from_candid_opt_n53(_uploadFile, _downloadFile, value.approvalTimestamp)),
        approved: value.approved,
        replyFile: record_opt_to_undefined(await from_candid_opt_n47(_uploadFile, _downloadFile, value.replyFile)),
        price: value.price
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    banner: null;
} | {
    offset: null;
} | {
    design: null;
} | {
    digital: null;
}): ServiceType {
    return "banner" in value ? ServiceType.banner : "offset" in value ? ServiceType.offset : "design" in value ? ServiceType.design : "digital" in value ? ServiceType.digital : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerPending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    workInProgress: null;
} | {
    accepted: null;
} | {
    draft: null;
} | {
    negotiating: null;
} | {
    paymentPending: null;
}): QuotationStatus {
    return "customerPending" in value ? QuotationStatus.customerPending : "completed" in value ? QuotationStatus.completed : "rejected" in value ? QuotationStatus.rejected : "workInProgress" in value ? QuotationStatus.workInProgress : "accepted" in value ? QuotationStatus.accepted : "draft" in value ? QuotationStatus.draft : "negotiating" in value ? QuotationStatus.negotiating : "paymentPending" in value ? QuotationStatus.paymentPending : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    needed: null;
} | {
    ready: null;
}): DesignStatus {
    return "needed" in value ? DesignStatus.needed : "ready" in value ? DesignStatus.ready : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminInvitationEntry>): Array<AdminInvitationEntry> {
    return value.map((x)=>from_candid_AdminInvitationEntry_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUser>): Array<AdminUser> {
    return value.map((x)=>from_candid_AdminUser_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuotationRequest>): Array<QuotationRequest> {
    return value.map((x)=>from_candid_QuotationRequest_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n41(_uploadFile, _downloadFile, x));
}
function to_candid_DesignStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStatus): _DesignStatus {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_QuotationStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): _QuotationStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignStatus): {
    needed: null;
} | {
    ready: null;
} {
    return value == DesignStatus.needed ? {
        needed: null
    } : value == DesignStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuotationStatus): {
    customerPending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    workInProgress: null;
} | {
    accepted: null;
} | {
    draft: null;
} | {
    negotiating: null;
} | {
    paymentPending: null;
} {
    return value == QuotationStatus.customerPending ? {
        customerPending: null
    } : value == QuotationStatus.completed ? {
        completed: null
    } : value == QuotationStatus.rejected ? {
        rejected: null
    } : value == QuotationStatus.workInProgress ? {
        workInProgress: null
    } : value == QuotationStatus.accepted ? {
        accepted: null
    } : value == QuotationStatus.draft ? {
        draft: null
    } : value == QuotationStatus.negotiating ? {
        negotiating: null
    } : value == QuotationStatus.paymentPending ? {
        paymentPending: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    banner: null;
} | {
    offset: null;
} | {
    design: null;
} | {
    digital: null;
} {
    return value == ServiceType.banner ? {
        banner: null
    } : value == ServiceType.offset ? {
        offset: null
    } : value == ServiceType.design ? {
        design: null
    } : value == ServiceType.digital ? {
        digital: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
