/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminInvitationEntry {
  'invitedBy' : [] | [Principal],
  'email' : string,
  'invitationTimestamp' : bigint,
  'hashedPassword' : string,
  'registrationMethod' : string,
}
export interface AdminUser {
  'principal' : [] | [Principal],
  'active' : boolean,
  'registrationTimestamp' : bigint,
  'registrationMethod' : string,
}
export interface ChatMessage {
  'id' : string,
  'senderIsOwner' : boolean,
  'messageText' : string,
  'isReply' : boolean,
  'originalMessageId' : [] | [string],
  'replyToMessageId' : [] | [string],
  'timestamp' : bigint,
  'senderName' : string,
  'senderEmail' : string,
}
export interface ContactInfo {
  'mapsLink' : string,
  'email' : string,
  'physicalAddress' : string,
  'phone' : string,
}
export interface DeliveryConfig { 'minimumFee' : bigint, 'perKmRate' : bigint }
export type ExternalBlob = Uint8Array;
export interface NegotiationMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface OfficeLocation {
  'lat' : number,
  'lon' : number,
  'address' : string,
}
export interface Project {
  'id' : string,
  'title' : string,
  'dateCompleted' : bigint,
  'description' : string,
  'imageUrl' : string,
  'category' : ServiceType,
}
export interface QuotationDetails {
  'terms' : string,
  'description' : string,
  'approvalTimestamp' : [] | [bigint],
  'approved' : boolean,
  'replyFile' : [] | [ExternalBlob],
  'price' : bigint,
}
export interface QuotationRequest {
  'id' : string,
  'status' : QuotationStatus,
  'serviceType' : ServiceType,
  'customer' : Principal,
  'mobileNumber' : string,
  'deadline' : bigint,
  'email' : string,
  'negotiationHistory' : Array<NegotiationMessage>,
  'timestamp' : bigint,
  'projectDetails' : string,
  'quotationFileBlob' : [] | [ExternalBlob],
}
export type QuotationStatus = { 'customerPending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'workInProgress' : null } |
  { 'accepted' : null } |
  { 'draft' : null } |
  { 'negotiating' : null } |
  { 'paymentPending' : null };
export interface Review {
  'id' : string,
  'customerName' : string,
  'projectType' : ServiceType,
  'reviewText' : string,
  'imageUrl' : [] | [string],
  'submissionDate' : bigint,
  'rating' : bigint,
}
export type ServiceType = { 'banner' : null } |
  { 'offset' : null } |
  { 'design' : null } |
  { 'digital' : null };
export interface UserProfile {
  'name' : string,
  'mobileNumber' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInternetIdentityAdmin' : ActorMethod<[Principal], undefined>,
  'addProject' : ActorMethod<[string, string, string, ServiceType], string>,
  'addQuotationDetails' : ActorMethod<
    [string, bigint, string, string],
    undefined
  >,
  'addReplyFile' : ActorMethod<[string, ExternalBlob], undefined>,
  'addReview' : ActorMethod<
    [string, string, bigint, [] | [string], ServiceType],
    string
  >,
  'adminAcceptPayment' : ActorMethod<[string], undefined>,
  'approveQuotation' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateDeliveryFee' : ActorMethod<[bigint], bigint>,
  'createQuotationRequest' : ActorMethod<
    [ServiceType, bigint, string, string, string, [] | [ExternalBlob]],
    string
  >,
  'customerApproveQuotation' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'editProject' : ActorMethod<
    [string, string, string, string, ServiceType],
    undefined
  >,
  'getAdminInvitations' : ActorMethod<[], Array<AdminInvitationEntry>>,
  'getAdminPrincipals' : ActorMethod<[], Array<AdminUser>>,
  'getAdminUserCount' : ActorMethod<[], bigint>,
  'getAllChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllQuotations' : ActorMethod<[], Array<QuotationRequest>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatsForCustomer' : ActorMethod<[string], Array<ChatMessage>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getCustomerChatHistory' : ActorMethod<
    [string],
    { 'messages' : Array<ChatMessage>, 'replies' : Array<ChatMessage> }
  >,
  'getDeliveryConfig' : ActorMethod<[], DeliveryConfig>,
  'getLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getMyQuotations' : ActorMethod<[], Array<QuotationRequest>>,
  'getOfficeLocation' : ActorMethod<[], [] | [OfficeLocation]>,
  'getPendingQuotationsOlderThan1Hour' : ActorMethod<[], Array<string>>,
  'getProjectsByCategory' : ActorMethod<[ServiceType], Array<Project>>,
  'getQuotationDetails' : ActorMethod<[string], [] | [QuotationDetails]>,
  'getQuotationStatistics' : ActorMethod<
    [],
    {
      'customerPending' : bigint,
      'completed' : bigint,
      'rejected' : bigint,
      'workInProgress' : bigint,
      'accepted' : bigint,
      'draft' : bigint,
      'negotiating' : bigint,
      'paymentPending' : bigint,
    }
  >,
  'getReplyFile' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getReviewsByRating' : ActorMethod<[bigint], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'handleQuotationResponse' : ActorMethod<
    [string, QuotationStatus, [] | [string]],
    undefined
  >,
  'inviteAdminUser' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markQuotationCustomerPending' : ActorMethod<[string], undefined>,
  'ownerReply' : ActorMethod<[string, string], string>,
  'registerBiometric' : ActorMethod<[string], undefined>,
  'respondToNegotiation' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], string>,
  'setDeliveryConfig' : ActorMethod<[bigint, bigint], undefined>,
  'setLogo' : ActorMethod<[ExternalBlob], undefined>,
  'setOfficeLocation' : ActorMethod<[OfficeLocation], undefined>,
  'updateContactInfo' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'verifyAuthentication' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];