/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceType = IDL.Variant({
  'banner' : IDL.Null,
  'offset' : IDL.Null,
  'design' : IDL.Null,
  'digital' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminInvitationEntry = IDL.Record({
  'invitedBy' : IDL.Opt(IDL.Principal),
  'email' : IDL.Text,
  'invitationTimestamp' : IDL.Int,
  'hashedPassword' : IDL.Text,
  'registrationMethod' : IDL.Text,
});
export const AdminUser = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'active' : IDL.Bool,
  'registrationTimestamp' : IDL.Int,
  'registrationMethod' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'senderIsOwner' : IDL.Bool,
  'messageText' : IDL.Text,
  'isReply' : IDL.Bool,
  'originalMessageId' : IDL.Opt(IDL.Text),
  'replyToMessageId' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'dateCompleted' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : ServiceType,
});
export const QuotationStatus = IDL.Variant({
  'customerPending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'workInProgress' : IDL.Null,
  'accepted' : IDL.Null,
  'draft' : IDL.Null,
  'negotiating' : IDL.Null,
  'paymentPending' : IDL.Null,
});
export const NegotiationMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const QuotationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : QuotationStatus,
  'serviceType' : ServiceType,
  'customer' : IDL.Principal,
  'mobileNumber' : IDL.Text,
  'deadline' : IDL.Int,
  'email' : IDL.Text,
  'negotiationHistory' : IDL.Vec(NegotiationMessage),
  'timestamp' : IDL.Int,
  'projectDetails' : IDL.Text,
  'quotationFileBlob' : IDL.Opt(ExternalBlob),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'projectType' : ServiceType,
  'reviewText' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'submissionDate' : IDL.Int,
  'rating' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'email' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'mapsLink' : IDL.Text,
  'email' : IDL.Text,
  'physicalAddress' : IDL.Text,
  'phone' : IDL.Text,
});
export const DeliveryConfig = IDL.Record({
  'minimumFee' : IDL.Int,
  'perKmRate' : IDL.Int,
});
export const OfficeLocation = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'address' : IDL.Text,
});
export const QuotationDetails = IDL.Record({
  'terms' : IDL.Text,
  'description' : IDL.Text,
  'approvalTimestamp' : IDL.Opt(IDL.Int),
  'approved' : IDL.Bool,
  'replyFile' : IDL.Opt(ExternalBlob),
  'price' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addInternetIdentityAdmin' : IDL.Func([IDL.Principal], [], []),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType],
      [IDL.Text],
      [],
    ),
  'addQuotationDetails' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addReplyFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'addReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Opt(IDL.Text), ServiceType],
      [IDL.Text],
      [],
    ),
  'adminAcceptPayment' : IDL.Func([IDL.Text], [], []),
  'approveQuotation' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateDeliveryFee' : IDL.Func([IDL.Int], [IDL.Int], ['query']),
  'createQuotationRequest' : IDL.Func(
      [
        ServiceType,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'customerApproveQuotation' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'editProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType],
      [],
      [],
    ),
  'getAdminInvitations' : IDL.Func(
      [],
      [IDL.Vec(AdminInvitationEntry)],
      ['query'],
    ),
  'getAdminPrincipals' : IDL.Func([], [IDL.Vec(AdminUser)], ['query']),
  'getAdminUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllQuotations' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatsForCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getCustomerChatHistory' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'messages' : IDL.Vec(ChatMessage),
          'replies' : IDL.Vec(ChatMessage),
        }),
      ],
      ['query'],
    ),
  'getDeliveryConfig' : IDL.Func([], [DeliveryConfig], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getMyQuotations' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
  'getOfficeLocation' : IDL.Func([], [IDL.Opt(OfficeLocation)], ['query']),
  'getPendingQuotationsOlderThan1Hour' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getProjectsByCategory' : IDL.Func(
      [ServiceType],
      [IDL.Vec(Project)],
      ['query'],
    ),
  'getQuotationDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(QuotationDetails)],
      ['query'],
    ),
  'getQuotationStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'customerPending' : IDL.Nat,
          'completed' : IDL.Nat,
          'rejected' : IDL.Nat,
          'workInProgress' : IDL.Nat,
          'accepted' : IDL.Nat,
          'draft' : IDL.Nat,
          'negotiating' : IDL.Nat,
          'paymentPending' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getReplyFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getReviewsByRating' : IDL.Func([IDL.Int], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'handleQuotationResponse' : IDL.Func(
      [IDL.Text, QuotationStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'inviteAdminUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markQuotationCustomerPending' : IDL.Func([IDL.Text], [], []),
  'ownerReply' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'registerBiometric' : IDL.Func([IDL.Text], [], []),
  'respondToNegotiation' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'setDeliveryConfig' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'setLogo' : IDL.Func([ExternalBlob], [], []),
  'setOfficeLocation' : IDL.Func([OfficeLocation], [], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'verifyAuthentication' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceType = IDL.Variant({
    'banner' : IDL.Null,
    'offset' : IDL.Null,
    'design' : IDL.Null,
    'digital' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminInvitationEntry = IDL.Record({
    'invitedBy' : IDL.Opt(IDL.Principal),
    'email' : IDL.Text,
    'invitationTimestamp' : IDL.Int,
    'hashedPassword' : IDL.Text,
    'registrationMethod' : IDL.Text,
  });
  const AdminUser = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'active' : IDL.Bool,
    'registrationTimestamp' : IDL.Int,
    'registrationMethod' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'senderIsOwner' : IDL.Bool,
    'messageText' : IDL.Text,
    'isReply' : IDL.Bool,
    'originalMessageId' : IDL.Opt(IDL.Text),
    'replyToMessageId' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'dateCompleted' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : ServiceType,
  });
  const QuotationStatus = IDL.Variant({
    'customerPending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'workInProgress' : IDL.Null,
    'accepted' : IDL.Null,
    'draft' : IDL.Null,
    'negotiating' : IDL.Null,
    'paymentPending' : IDL.Null,
  });
  const NegotiationMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const QuotationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : QuotationStatus,
    'serviceType' : ServiceType,
    'customer' : IDL.Principal,
    'mobileNumber' : IDL.Text,
    'deadline' : IDL.Int,
    'email' : IDL.Text,
    'negotiationHistory' : IDL.Vec(NegotiationMessage),
    'timestamp' : IDL.Int,
    'projectDetails' : IDL.Text,
    'quotationFileBlob' : IDL.Opt(ExternalBlob),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'projectType' : ServiceType,
    'reviewText' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'submissionDate' : IDL.Int,
    'rating' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'email' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'mapsLink' : IDL.Text,
    'email' : IDL.Text,
    'physicalAddress' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DeliveryConfig = IDL.Record({
    'minimumFee' : IDL.Int,
    'perKmRate' : IDL.Int,
  });
  const OfficeLocation = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'address' : IDL.Text,
  });
  const QuotationDetails = IDL.Record({
    'terms' : IDL.Text,
    'description' : IDL.Text,
    'approvalTimestamp' : IDL.Opt(IDL.Int),
    'approved' : IDL.Bool,
    'replyFile' : IDL.Opt(ExternalBlob),
    'price' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addInternetIdentityAdmin' : IDL.Func([IDL.Principal], [], []),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType],
        [IDL.Text],
        [],
      ),
    'addQuotationDetails' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addReplyFile' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'addReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Opt(IDL.Text), ServiceType],
        [IDL.Text],
        [],
      ),
    'adminAcceptPayment' : IDL.Func([IDL.Text], [], []),
    'approveQuotation' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateDeliveryFee' : IDL.Func([IDL.Int], [IDL.Int], ['query']),
    'createQuotationRequest' : IDL.Func(
        [
          ServiceType,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'customerApproveQuotation' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'editProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType],
        [],
        [],
      ),
    'getAdminInvitations' : IDL.Func(
        [],
        [IDL.Vec(AdminInvitationEntry)],
        ['query'],
      ),
    'getAdminPrincipals' : IDL.Func([], [IDL.Vec(AdminUser)], ['query']),
    'getAdminUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllQuotations' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatsForCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getCustomerChatHistory' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'messages' : IDL.Vec(ChatMessage),
            'replies' : IDL.Vec(ChatMessage),
          }),
        ],
        ['query'],
      ),
    'getDeliveryConfig' : IDL.Func([], [DeliveryConfig], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getMyQuotations' : IDL.Func([], [IDL.Vec(QuotationRequest)], ['query']),
    'getOfficeLocation' : IDL.Func([], [IDL.Opt(OfficeLocation)], ['query']),
    'getPendingQuotationsOlderThan1Hour' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getProjectsByCategory' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'getQuotationDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(QuotationDetails)],
        ['query'],
      ),
    'getQuotationStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'customerPending' : IDL.Nat,
            'completed' : IDL.Nat,
            'rejected' : IDL.Nat,
            'workInProgress' : IDL.Nat,
            'accepted' : IDL.Nat,
            'draft' : IDL.Nat,
            'negotiating' : IDL.Nat,
            'paymentPending' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getReplyFile' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getReviewsByRating' : IDL.Func([IDL.Int], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'handleQuotationResponse' : IDL.Func(
        [IDL.Text, QuotationStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'inviteAdminUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markQuotationCustomerPending' : IDL.Func([IDL.Text], [], []),
    'ownerReply' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'registerBiometric' : IDL.Func([IDL.Text], [], []),
    'respondToNegotiation' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'setDeliveryConfig' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'setLogo' : IDL.Func([ExternalBlob], [], []),
    'setOfficeLocation' : IDL.Func([OfficeLocation], [], []),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyAuthentication' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };